import { build } from "bun";
import { resolve } from "path";

const entrypoint = resolve(import.meta.dir, "src/utils/binary-worker.ts");
const outfile = resolve(import.meta.dir, "src/utils/binary-worker-code.ts");

console.log(`Bundling worker from ${entrypoint}...`);

const result = await build({
  entrypoints: [entrypoint],
  target: "node",
  minify: true,
  // We want to inline dependencies like uuid, but keep node built-ins external
  external: ["worker_threads", "v8", "vm", "fs", "path", "os", "events", "stream", "util", "buffer"],
});

if (!result.success) {
  console.error("Worker build failed");
  for (const msg of result.logs) {
    console.error(msg);
  }
  process.exit(1);
}

const text = await result.outputs[0].text();

const code = `// @ts-nocheck
/* eslint-disable */
// Auto-generated by build-worker.ts - DO NOT EDIT
export const binaryWorkerCode = ${JSON.stringify(text)};
`;

await Bun.write(outfile, code);
console.log(`Worker code bundled to ${outfile} (${(text.length / 1024).toFixed(2)} KB)`);
