export type ColumnMeta = {
    isJson?: boolean;
    enumValues?: readonly string[];
    autoGenerate?: {
        type: 'uuid';
        version?: 1 | 3 | 4 | 5 | 6 | 7;
    };
    isPrimaryKey?: boolean;
    default?: any;
    defaultFn?: (row: Record<string, any>) => any;
    references?: {
        table: string;
        column: string;
        onDelete?: 'cascade' | 'set null' | 'restrict' | 'no action';
        onUpdate?: 'cascade' | 'set null' | 'restrict' | 'no action';
    };
    codec?: string;
    materialized?: string;
    alias?: string;
    defaultExpr?: string;
    comment?: string;
};
export declare class ClickHouseColumn<TType = any, TNotNull extends boolean = true, TAutoGenerated extends boolean = false> {
    name: string;
    type: string;
    isNull: boolean;
    meta?: ColumnMeta | undefined;
    tableName?: string;
    constructor(name: string, type: string, isNull?: boolean, // Columns are NOT NULL by default (isNull = false)
    meta?: ColumnMeta | undefined);
    clone<NTNotNull extends boolean = TNotNull, NAutoGenerated extends boolean = TAutoGenerated>(overrides?: {
        name?: string;
        type?: string;
        isNull?: boolean;
        meta?: ColumnMeta;
    }): ClickHouseColumn<TType, NTNotNull, NAutoGenerated>;
    notNull(): ClickHouseColumn<TType, true, TAutoGenerated>;
    nullable(): ClickHouseColumn<TType, false, TAutoGenerated>;
    autoGenerate(options?: {
        version?: 1 | 3 | 4 | 5 | 6 | 7;
    }): ClickHouseColumn<TType, TNotNull, true>;
    primaryKey(): ClickHouseColumn<TType, true, TAutoGenerated>;
    /**
     * Define a default value for the column.
     * Can be a static value or a SQL expression like 'now()'.
     */
    default(value: any): ClickHouseColumn<TType, TNotNull, TAutoGenerated>;
    references(getColumn: () => ClickHouseColumn, options?: {
        onDelete?: 'cascade' | 'set null' | 'restrict' | 'no action';
        onUpdate?: 'cascade' | 'set null' | 'restrict' | 'no action';
    }): ClickHouseColumn<TType, TNotNull, TAutoGenerated>;
    /**
     * Add a comment to the column in the database.
     */
    comment(text: string): ClickHouseColumn<TType, TNotNull, TAutoGenerated>;
    alias(expression: string): ClickHouseColumn<TType, TNotNull, TAutoGenerated>;
    /**
     * Apply a compression codec to this column.
     * Can be chained to apply multiple codecs (e.g., Delta then ZSTD).
     *
     * @example
     * ```typescript
     * // Optimize for time-series
     * timestamp.codec('DoubleDelta').codec('ZSTD', 3)
     * // Optimize for metrics
     * value.codec('Gorilla')
     * ```
     */
    codec(type: 'ZSTD' | 'LZ4' | 'Delta' | 'DoubleDelta' | 'Gorilla' | 'None', level?: number): ClickHouseColumn<TType, TNotNull, TAutoGenerated>;
    /**
     * Calculates the column value on the client side before insertion.
     * Useful for UUIDs, hashes, or computations based on other fields.
     */
    $defaultFn(fn: (row: Record<string, any>) => any): ClickHouseColumn<TType, TNotNull, TAutoGenerated>;
    toSQL(): string;
}
